name: Java CI

on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Bump version
      run: bash bump.sh
    
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "[ci skip] (actions) Bump version."
  build:
    runs-on: ubuntu-latest
    needs: [bump]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build
    
    - uses: actions/upload-artifact@v3
      with:
        name: slimeplus-jars
        path: build/libs/*.jar

    - id: version
      name: Get version
      run: echo "::set-output name=version::$(cat .version)"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/*.jar"
        body: "This is an automated release."
        name: "v${{ steps.version.outputs.version }}"
        draft: false
        tag: "v${{ steps.version.outputs.version }}"
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
